name = "10xdevsproject"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
name = "10xdevsproject"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"

# KV binding for sessions
[[env.production.kv_namespaces]]
binding = "SESSION"
id = "fd3a5c33d26346f6ad7c5ee4a24e888d"
preview_id = "fd3a5c33d26346f6ad7c5ee4a24e888d"